export const LOGIN = "LOGIN";
export const LOGIN__SUCCESS = "LOGIN__SUCCESS";
export const LOGIN__FAIL = "LOGIN__FAIL";
export const SIGNUP = "SIGNUP";
export const SIGNUP__FAIL = "SIGNUP__FAIL";
export const SIGNUP__SUCCESS = "SIGNUP_SUCCESS";
export const OPEN__LOGIN = "OPEN__LOGIN";
export const CLOSE__LOGIN = "CLOSE__LOGIN";

export const CLEARE__ERROR = "CLEARE__ERROR";

export const FETCH__NEWSFEED = "FETCH_NEWSFEED";
export const FETCH__NEWSFEED__SUCCESS = "FETCH__NEWSFEED__SUCCESS";
export const FETCH__NEWSFEED__FAIL = "FETCH__NEWSFEED__FAIL";

export const POST__NEWSFEED = "POST__NEWSFEED";
export const POST__NEWSFEED__SUCCESS = "POST__NEWSFEED__SUCCESS";
export const POST__NEWSFEED__FAIL = "POST__NEWSFEED__FAIL";

export const FETCH__NEWSFEED__COMMENT = "FETCH__NEWSFEED__COMMENT";
export const FETCH__NEWSFEED__COMMENT__SUCCESS = "FETCH__NEWSFEED__COMMENT__SUCCESS";
export const FETCH__NEWSFEED__COMMENT__FAIL = "FETCH__NEWSFEED__COMMENT__FAIL";

export const LIKE__NEWSFEED = "LIKE__NEWSFEED";
export const LIKE__NEWSFEED__SUCCESS = "LIKE__NEWSFEED__SUCCESS";
export const LIKE__NEWSFEED__FAIL = "LIKE__NEWSFEED__FAIL";

export const DISLIKE__NEWSFEED = "DISLIKE__NEWSFEED";
export const DISLIKE__NEWSFEED__SUCCESS = "DISLIKE__NEWSFEED__SUCCESS";
export const DISLIKE__NEWSFEED__FAIL = "DISLIKE__NEWSFEED__FAIL";

export const POST__NEWSFEED__COMMENT = "POST__NEWSFEED__COMMENT";
export const POST__NEWSFEED__COMMENT__SUCCESS = "POST__NEWSFEED__COMMENT__SUCCESS";
export const POST__NEWSFEED__COMMENT__FAIL = "POST__NEWSFEED__COMMENT__SUCCESS";

export const GET__USER = "GET__USER";
export const GET__USER__SUCCESS = "GET__USER__SUCCESS"
export const GET__USER__FAIL = "GET__USER__FAIL";

export const FETCH__NOTIFICATION = "FETCH__NOTIFICATION";
export const FETCH__NOTIFICATION__SUCCESS = "FETCH__NOTIFICATION__SUCCESS";
export const FETCH__NOTIFICATION__FAIL = "FETCH__NOTIFICATION__FAIL";

export const SEEN__NOTIFICATION = "SEEN__NOTIFICATION";
export const SEEN__NOTIFICATION__SUCCESS = "SEEN__NOTIFICATION__SUCCESS";
export const SEEN__NOTIFICATION__FAIL = "SEEN__NOTIFICATION__FAIL";

export const FETCH__NEWSFEED__USER__NOW = "FETCH__NEWSFEED__USER__NOW";
export const FETCH__NEWSFEED__USER__NOW__SUCCESS = "FETCH__NEWSFEED__USER__NOW__SUCCESS";
export const FETCH__NEWSFEED__USER__NOW__FAIL = "FETCH__NEWSFEED__USER__NOW__FAIL";

export const FETCH__ANOTHER__PROFILE = "FETCH__ANOTHER__PROFILE";
export const FETCH__ANOTHER__PROFILE__SUCCESS = "FETCH__ANOTHER__PROFILE__SUCCESS";
export const FETCH__ANOTHER__PROFILE__FAIL = "FETCH__ANOTHER__PROFILE__FAIL";

export const FETCH__ANOTHER__NEWSFEED = "FETCH__ANOTHER__NEWSFEED";
export const FETCH__ANOTHER__NEWSFEED__SUCCESS = "FETCH__ANOTHER__NEWSFEED__CUCCESS";
export const FETCH__ANOTHER__NEWFEED__FAIL = "FETCH__ANOTHER__NEWSFEED__FAIL";

export const OPEN__MESSAGEITEM = "OPEN__MESSAGEITEM";
export const CLOSE__MESSAGEITEM = "CLOSE__MESSAGEITEM";

export const RECIEVER__MESSAGE = "RECIEVER__MESSAGE";

export const INCREASE__NOTIFICATION__MESSAGE = "INCREASE__NOTIFICATION__MESSAGE";

export const FETCH__MY__MESSAGE = "FETCH__MY__MESSAGE";
export const FETCH__MY__MESSAGE__SUCCESS = "FETCH__MY__MESSAGE__SUCCESS";
export const FETCH__MY__MESSAGE__FAIL = "FETCH__MY__MESSAGE__FAIL";

export const FETCH__SEEN__MESSAGE = "FETCH__SEEN__MESSAGE";

export const VOTE__PROFILE__USER = "VOTE__PROFILE__USER";
export const VOTE__PROFILE__USER__SUCCESS = "VOTE__PROFILE__USER__SUCCESS";
export const VOTE__PROFILE__USER__FAIL = "VOTE__PROFILE__USER__FAIL";

export const DOWN__PROFILE__USER = "DOWN__PROFILE__USER";
export const DOWN__PROFILE__USER__SUCCESS = "DOWN__PROFILE__USER__SUCCESS";
export const DOWN__PROFILE__USER__FAIL = "DOWN__PROFILE__USER__FAIL";

export const UPDATE__PROFILE__USER = "UPDATE__PROFILE__USER";
export const UPDATE__PROFILE__USER__SUCCESS = "UPDATE__PROFILE__USER__SUCCESS";
export const UPDATE__PROFILE__USER__FAIL = "UPDATE__PROFILE__USER__FAIL";

export const POST__UPDATE__PROFILE__USER = "POST__UPDATE__PROFILE__USER";

export const FETCH__ROOM__HOTEL = "FETCH__ROOM__HOTEL";
export const FETCH__ROOM__HOTEL__SUCCESS = "FETCH__ROOM__HOTEL__SUCCESS";
export const FETCH__ROOM__HOTEL__FAIL = "FETCH__ROOM__HOTEL__FAIL";

export const FETCH__DETAIL__ROOM = "FETCH__DETAIL__ROOM";
export const FETCH__DETAIL__ROOM__SUCCESS = "FETCH__DETAIL__ROOM__SUCCESS";
export const FETCH__DETAIL__ROOM__FAIL = "FETCH__DETAIL__ROOM__FAIL";

export const FETCH__ANOTHER__ROOM = "FETCH__ANOTHER__ROOM";
export const FETCH__ANOTHER__ROOM__SUCCESS = "FETCH__ANOTHER__ROOM__SUCCESS"
export const FETCH__ANOTHER__ROOM__FAIL = "FETCH__ANOTHER__ROOM__FAIL"

export const LOGOUT = "LOGOUT";

export const TOGGLE__OPEN__MESSAGE = "TOGGLE__OPEN__MESSAGE";
export const TOGGLE__OPEN__NOTIFICATION = "TOGGLE__OPEN__NOTIFICATION";

export const TOGGLE__OPEN__MESSAGE__CLOSE = "TOGGLE__OPEN__MESSAGE__CLOSE";
export const TOGGLE__OPEN__NOTIFICATION__CLOSE = "TOGGLE__OPEN__NOTIFICATION__CLOSE";